name: Build LaTeX document

on:
  push:
    branches:
      - master

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          run: |
            apk add make
            make
          root_file: |
            ./resume.tex
            ./resume_photo.tex
            ./resume-zh_CN.tex
          latexmk_use_xelatex: True
