name: Build resume tex files in zh-CN

on:
  push:
    branches:
      - zh-CN

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: |
            ./resume.tex
            ./resume_photo.tex
            ./resume-zh_CN.tex
          latexmk_use_xelatex: True
          post_compile: "latexmk -c"

      - name: Upload pdf
        uses: actions/upload-artifact@v2
        with:
          name: resume_pdf_zh-CN
          path: ./resume*.pdf
